package sample

// Code generated by typehash-gen. DO NOT EDIT.

func (v T1) TypeHash() string {
	return "072743820631b7d08b32eb97a7ba6c5c"
}

func (v T2) TypeHash() string {
	return "072743820631b7d08b32eb97a7ba6c5c"
}
