package generator

const (
	FileTemplate = `
{{$data := .}}
package {{$data.PkgName}}

// Code generated by typehash-gen. DO NOT EDIT.

{{range $idx, $tp := $data.Types}}
	{{$tp.FuncCode}}
{{end}}
`
)
